language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bubionbreakfast/restaurant-app -f Dockerfile.dev .    

script:
    - docker run -e CI=true bubionbreakfast/restaurant-app npm run test   